---
- hosts: dev
  become: true
  tasks:

    - name: Pull default Docker image
      shell: "sudo docker pull {{ default_container_image }}"
# Creates the number of containers defined by the variable create_containers, using values from vars file
    - name: Restart a container
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: started
        restart: yes
        ports:
          - "8085:8080"
