---
- hosts: dev
  become: true
  vars_files:
    - default.yml
  tasks:
    - name: Restart a container
      docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: started
        restart: yes
        ports:
         - "8085:8080"
